import mysql from "mysql2/promise";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error("DATABASE_URL not set"); process.exit(1); }

const conn = await mysql.createConnection(DATABASE_URL);

// ─── Cities ──────────────────────────────────────────────────────────
const cities = [
  { nameEn: "Riyadh", nameAr: "الرياض", slug: "riyadh", descriptionEn: "The capital city of Saudi Arabia and the largest city in the Arabian Peninsula. Riyadh is a modern metropolis that blends traditional Arabian culture with cutting-edge architecture and world-class entertainment.", descriptionAr: "عاصمة المملكة العربية السعودية وأكبر مدينة في شبه الجزيرة العربية. الرياض مدينة عصرية تجمع بين الثقافة العربية الأصيلة والعمارة الحديثة والترفيه العالمي.", latitude: "24.7136", longitude: "46.6753", isActive: true },
  { nameEn: "Jeddah", nameAr: "جدة", slug: "jeddah", descriptionEn: "The commercial capital of Saudi Arabia and gateway to the Holy Cities. Jeddah is known for its vibrant culture, historic Al-Balad district, stunning Red Sea coastline, and cosmopolitan atmosphere.", descriptionAr: "العاصمة التجارية للمملكة العربية السعودية وبوابة الحرمين الشريفين. تشتهر جدة بثقافتها النابضة وحيها التاريخي البلد وساحل البحر الأحمر الخلاب وأجوائها العالمية.", latitude: "21.4858", longitude: "39.1925", isActive: true },
  { nameEn: "Madinah", nameAr: "المدينة المنورة", slug: "madinah", descriptionEn: "The radiant city and second holiest city in Islam. Madinah welcomes millions of pilgrims and visitors annually, offering a unique blend of spiritual significance and modern hospitality.", descriptionAr: "المدينة المنورة ثاني أقدس مدينة في الإسلام. تستقبل المدينة ملايين الحجاج والزوار سنوياً، وتقدم مزيجاً فريداً من الأهمية الروحية والضيافة الحديثة.", latitude: "24.4672", longitude: "39.6024", isActive: true },
];

for (const city of cities) {
  await conn.execute(
    "INSERT INTO cities (nameEn, nameAr, slug, descriptionEn, descriptionAr, latitude, longitude, isActive) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE nameAr=VALUES(nameAr)",
    [city.nameEn, city.nameAr, city.slug, city.descriptionEn, city.descriptionAr, city.latitude, city.longitude, city.isActive]
  );
}
console.log("✅ Cities seeded");

// Get city IDs
const [cityRows] = await conn.execute("SELECT id, slug FROM cities");
const cityMap = {};
for (const r of cityRows) cityMap[r.slug] = r.id;

// ─── Neighborhoods ───────────────────────────────────────────────────
const riyadhNeighborhoods = [
  { nameEn: "Al Olaya", nameAr: "العليا", slug: "al-olaya", zone: "Central", lat: 24.6944, lng: 46.6853, avgAdrPeak: 1200, avgAdrHigh: 900, avgAdrLow: 600, avgNightlyRate: 800, walkTimeToLandmark: "5 min to Kingdom Tower", descriptionEn: "The premier business and commercial district of Riyadh, home to Kingdom Tower and luxury hotels.", descriptionAr: "الحي التجاري الرئيسي في الرياض، موطن برج المملكة والفنادق الفاخرة.", landmarks: [{ name: "Kingdom Tower", nameAr: "برج المملكة" }, { name: "Al Faisaliah Tower", nameAr: "برج الفيصلية" }] },
  { nameEn: "Al Malqa", nameAr: "الملقا", slug: "al-malqa", zone: "North", lat: 24.8012, lng: 46.6358, avgAdrPeak: 1000, avgAdrHigh: 750, avgAdrLow: 500, avgNightlyRate: 700, walkTimeToLandmark: "10 min to KAFD", descriptionEn: "An upscale residential neighborhood in northern Riyadh, known for luxury villas and modern compounds.", descriptionAr: "حي سكني راقٍ في شمال الرياض، يشتهر بالفلل الفاخرة والمجمعات الحديثة.", landmarks: [{ name: "KAFD", nameAr: "مركز الملك عبدالله المالي" }] },
  { nameEn: "Al Nakheel", nameAr: "النخيل", slug: "al-nakheel", zone: "North", lat: 24.7672, lng: 46.6425, avgAdrPeak: 900, avgAdrHigh: 700, avgAdrLow: 450, avgNightlyRate: 650, walkTimeToLandmark: "8 min to Nakheel Mall", descriptionEn: "A prestigious residential area with tree-lined streets, upscale dining, and premium shopping.", descriptionAr: "منطقة سكنية مرموقة بشوارع مظللة بالأشجار ومطاعم راقية وتسوق متميز.", landmarks: [{ name: "Nakheel Mall", nameAr: "النخيل مول" }] },
  { nameEn: "Hittin", nameAr: "حطين", slug: "hittin", zone: "North", lat: 24.7789, lng: 46.6234, avgAdrPeak: 1100, avgAdrHigh: 850, avgAdrLow: 550, avgNightlyRate: 750, walkTimeToLandmark: "5 min to Riyadh Front", descriptionEn: "One of Riyadh's most sought-after neighborhoods, featuring modern villas and proximity to major attractions.", descriptionAr: "أحد أكثر أحياء الرياض طلباً، يتميز بالفلل الحديثة والقرب من المعالم الرئيسية.", landmarks: [{ name: "Riyadh Front", nameAr: "واجهة الرياض" }] },
  { nameEn: "Al Sahafah", nameAr: "الصحافة", slug: "al-sahafah", zone: "North", lat: 24.8156, lng: 46.6712, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 400, avgNightlyRate: 550, walkTimeToLandmark: "12 min to KAFD", descriptionEn: "A growing residential district with modern apartments and easy access to northern Riyadh's business hubs.", descriptionAr: "حي سكني متنامٍ بشقق حديثة وسهولة الوصول لمراكز الأعمال في شمال الرياض.", landmarks: [{ name: "Sahafa Park", nameAr: "حديقة الصحافة" }] },
  { nameEn: "Al Rabwah", nameAr: "الربوة", slug: "al-rabwah", zone: "Central", lat: 24.7234, lng: 46.7156, avgAdrPeak: 750, avgAdrHigh: 550, avgAdrLow: 380, avgNightlyRate: 500, walkTimeToLandmark: "10 min to Riyadh Gallery", descriptionEn: "A central residential area known for its family-friendly atmosphere and convenient location.", descriptionAr: "منطقة سكنية مركزية تشتهر بأجوائها العائلية وموقعها المناسب.", landmarks: [{ name: "Riyadh Gallery Mall", nameAr: "الرياض جاليري مول" }] },
  { nameEn: "Al Yasmin", nameAr: "الياسمين", slug: "al-yasmin", zone: "North", lat: 24.8234, lng: 46.6456, avgAdrPeak: 850, avgAdrHigh: 650, avgAdrLow: 420, avgNightlyRate: 600, walkTimeToLandmark: "15 min to KAFD", descriptionEn: "A modern residential neighborhood with wide streets, parks, and premium amenities.", descriptionAr: "حي سكني حديث بشوارع واسعة وحدائق ومرافق متميزة.", landmarks: [{ name: "Al Yasmin Park", nameAr: "حديقة الياسمين" }] },
  { nameEn: "Al Wurud", nameAr: "الورود", slug: "al-wurud", zone: "Central", lat: 24.7089, lng: 46.6789, avgAdrPeak: 900, avgAdrHigh: 700, avgAdrLow: 480, avgNightlyRate: 650, walkTimeToLandmark: "3 min to Tahlia Street", descriptionEn: "A vibrant neighborhood along Tahlia Street, Riyadh's premier dining and shopping destination.", descriptionAr: "حي نابض بالحياة على شارع التحلية، الوجهة الأولى للمطاعم والتسوق في الرياض.", landmarks: [{ name: "Tahlia Street", nameAr: "شارع التحلية" }] },
  { nameEn: "Al Sulimaniyah", nameAr: "السليمانية", slug: "al-sulimaniyah", zone: "Central", lat: 24.6912, lng: 46.6934, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 350, avgNightlyRate: 480, walkTimeToLandmark: "5 min to King Fahd Library", descriptionEn: "A historic central neighborhood with a mix of residential and commercial spaces.", descriptionAr: "حي مركزي تاريخي يجمع بين المساحات السكنية والتجارية.", landmarks: [{ name: "King Fahd National Library", nameAr: "مكتبة الملك فهد الوطنية" }] },
  { nameEn: "Al Murabba", nameAr: "المربع", slug: "al-murabba", zone: "Central", lat: 24.6456, lng: 46.7123, avgAdrPeak: 650, avgAdrHigh: 480, avgAdrLow: 320, avgNightlyRate: 420, walkTimeToLandmark: "Walking distance to National Museum", descriptionEn: "The historic heart of Riyadh, home to the National Museum and Murabba Palace.", descriptionAr: "قلب الرياض التاريخي، موطن المتحف الوطني وقصر المربع.", landmarks: [{ name: "National Museum", nameAr: "المتحف الوطني" }, { name: "Murabba Palace", nameAr: "قصر المربع" }] },
  { nameEn: "Al Rawdah", nameAr: "الروضة", slug: "al-rawdah", zone: "East", lat: 24.7345, lng: 46.7456, avgAdrPeak: 700, avgAdrHigh: 530, avgAdrLow: 350, avgNightlyRate: 480, walkTimeToLandmark: "10 min to Panorama Mall", descriptionEn: "A well-established residential area in eastern Riyadh with good connectivity.", descriptionAr: "منطقة سكنية راسخة في شرق الرياض بتوصيلات جيدة.", landmarks: [{ name: "Panorama Mall", nameAr: "بانوراما مول" }] },
  { nameEn: "Al Hamra", nameAr: "الحمراء", slug: "al-hamra-riyadh", zone: "Central", lat: 24.7012, lng: 46.7012, avgAdrPeak: 750, avgAdrHigh: 560, avgAdrLow: 380, avgNightlyRate: 520, walkTimeToLandmark: "7 min to Olaya Street", descriptionEn: "A central neighborhood known for its mix of residential villas and commercial establishments.", descriptionAr: "حي مركزي يشتهر بمزيج الفلل السكنية والمنشآت التجارية.", landmarks: [{ name: "Olaya Street", nameAr: "شارع العليا" }] },
  { nameEn: "Irqah", nameAr: "عرقة", slug: "irqah", zone: "West", lat: 24.7234, lng: 46.5678, avgAdrPeak: 950, avgAdrHigh: 720, avgAdrLow: 480, avgNightlyRate: 680, walkTimeToLandmark: "15 min to Diriyah", descriptionEn: "An exclusive residential area in western Riyadh, known for spacious villas and proximity to Diriyah.", descriptionAr: "منطقة سكنية حصرية في غرب الرياض، تشتهر بالفلل الواسعة والقرب من الدرعية.", landmarks: [{ name: "Wadi Hanifah", nameAr: "وادي حنيفة" }] },
  { nameEn: "Al Narjis", nameAr: "النرجس", slug: "al-narjis", zone: "North", lat: 24.8456, lng: 46.6234, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 400, avgNightlyRate: 560, walkTimeToLandmark: "20 min to KAFD", descriptionEn: "A rapidly developing neighborhood in northern Riyadh with modern residential complexes.", descriptionAr: "حي سريع التطور في شمال الرياض بمجمعات سكنية حديثة.", landmarks: [{ name: "Al Narjis Park", nameAr: "حديقة النرجس" }] },
  { nameEn: "Al Aqiq", nameAr: "العقيق", slug: "al-aqiq", zone: "North", lat: 24.7912, lng: 46.6123, avgAdrPeak: 950, avgAdrHigh: 720, avgAdrLow: 480, avgNightlyRate: 680, walkTimeToLandmark: "5 min to KAFD", descriptionEn: "A premium neighborhood adjacent to KAFD, attracting business travelers and professionals.", descriptionAr: "حي متميز مجاور لمركز الملك عبدالله المالي، يجذب رجال الأعمال والمهنيين.", landmarks: [{ name: "KAFD", nameAr: "مركز الملك عبدالله المالي" }] },
  { nameEn: "Al Thumama", nameAr: "الثمامة", slug: "al-thumama", zone: "North-East", lat: 24.8567, lng: 46.7234, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 300, avgNightlyRate: 400, walkTimeToLandmark: "Near Thumama Park", descriptionEn: "A developing area known for its desert parks and outdoor activities.", descriptionAr: "منطقة متطورة تشتهر بحدائقها الصحراوية والأنشطة الخارجية.", landmarks: [{ name: "Thumama National Park", nameAr: "حديقة الثمامة الوطنية" }] },
  { nameEn: "Al Diriyah", nameAr: "الدرعية", slug: "al-diriyah", zone: "West", lat: 24.7345, lng: 46.5723, avgAdrPeak: 1100, avgAdrHigh: 850, avgAdrLow: 550, avgNightlyRate: 750, walkTimeToLandmark: "At Diriyah Gate", descriptionEn: "The historic birthplace of the Saudi state, now a UNESCO World Heritage site and luxury tourism destination.", descriptionAr: "مسقط رأس الدولة السعودية التاريخي، الآن موقع تراث عالمي لليونسكو ووجهة سياحية فاخرة.", landmarks: [{ name: "Diriyah Gate", nameAr: "بوابة الدرعية" }, { name: "At-Turaif", nameAr: "الطريف" }] },
  { nameEn: "Al Mohammadiyah", nameAr: "المحمدية", slug: "al-mohammadiyah", zone: "North", lat: 24.7678, lng: 46.6567, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 400, avgNightlyRate: 560, walkTimeToLandmark: "10 min to Nakheel Mall", descriptionEn: "A well-planned residential neighborhood with modern amenities and green spaces.", descriptionAr: "حي سكني مخطط بعناية بمرافق حديثة ومساحات خضراء.", landmarks: [{ name: "Mohammadiyah Park", nameAr: "حديقة المحمدية" }] },
  { nameEn: "Al Ghadir", nameAr: "الغدير", slug: "al-ghadir", zone: "East", lat: 24.7456, lng: 46.7678, avgAdrPeak: 650, avgAdrHigh: 480, avgAdrLow: 320, avgNightlyRate: 430, walkTimeToLandmark: "15 min to Granada Center", descriptionEn: "An affordable residential area in eastern Riyadh with growing commercial activity.", descriptionAr: "منطقة سكنية بأسعار معقولة في شرق الرياض مع نشاط تجاري متنامٍ.", landmarks: [{ name: "Granada Center", nameAr: "مركز غرناطة" }] },
  { nameEn: "Al Malaz", nameAr: "الملز", slug: "al-malaz", zone: "Central", lat: 24.6678, lng: 46.7234, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 300, avgNightlyRate: 400, walkTimeToLandmark: "5 min to King Fahd Stadium", descriptionEn: "One of Riyadh's oldest neighborhoods, centrally located with sports facilities and parks.", descriptionAr: "أحد أقدم أحياء الرياض، يقع في المركز مع مرافق رياضية وحدائق.", landmarks: [{ name: "King Fahd Stadium", nameAr: "استاد الملك فهد" }] },
  { nameEn: "Al Shifa", nameAr: "الشفا", slug: "al-shifa", zone: "South", lat: 24.5912, lng: 46.7012, avgAdrPeak: 500, avgAdrHigh: 380, avgAdrLow: 250, avgNightlyRate: 350, walkTimeToLandmark: "Near Al Shifa Park", descriptionEn: "A residential neighborhood in southern Riyadh with affordable housing options.", descriptionAr: "حي سكني في جنوب الرياض بخيارات سكنية بأسعار معقولة.", landmarks: [{ name: "Al Shifa Park", nameAr: "حديقة الشفا" }] },
  { nameEn: "Al Arid", nameAr: "العارض", slug: "al-arid", zone: "North", lat: 24.8678, lng: 46.6567, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 350, avgNightlyRate: 480, walkTimeToLandmark: "Near King Salman Park", descriptionEn: "A developing area in far north Riyadh with new residential projects.", descriptionAr: "منطقة متطورة في أقصى شمال الرياض بمشاريع سكنية جديدة.", landmarks: [{ name: "King Salman Park (planned)", nameAr: "حديقة الملك سلمان (مخططة)" }] },
  { nameEn: "Al Wadi", nameAr: "الوادي", slug: "al-wadi", zone: "North", lat: 24.7789, lng: 46.6678, avgAdrPeak: 850, avgAdrHigh: 650, avgAdrLow: 430, avgNightlyRate: 600, walkTimeToLandmark: "8 min to KAFD", descriptionEn: "A premium residential area near KAFD with modern villas and apartments.", descriptionAr: "منطقة سكنية متميزة قرب مركز الملك عبدالله المالي بفلل وشقق حديثة.", landmarks: [{ name: "KAFD", nameAr: "مركز الملك عبدالله المالي" }] },
  { nameEn: "Tuwaiq", nameAr: "طويق", slug: "tuwaiq", zone: "West", lat: 24.6567, lng: 46.5912, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 300, avgNightlyRate: 400, walkTimeToLandmark: "Near Tuwaiq Palace", descriptionEn: "A western Riyadh neighborhood near the Tuwaiq escarpment with desert views.", descriptionAr: "حي في غرب الرياض قرب جرف طويق بإطلالات صحراوية.", landmarks: [{ name: "Tuwaiq Palace", nameAr: "قصر طويق" }] },
  { nameEn: "King Abdullah District", nameAr: "حي الملك عبدالله", slug: "king-abdullah-district", zone: "North", lat: 24.8123, lng: 46.6456, avgAdrPeak: 1000, avgAdrHigh: 780, avgAdrLow: 520, avgNightlyRate: 720, walkTimeToLandmark: "At KAFD", descriptionEn: "The financial district of Riyadh, home to KAFD and major corporate headquarters.", descriptionAr: "الحي المالي في الرياض، موطن مركز الملك عبدالله المالي ومقرات الشركات الكبرى.", landmarks: [{ name: "KAFD", nameAr: "مركز الملك عبدالله المالي" }, { name: "KAFD Conference Center", nameAr: "مركز مؤتمرات كافد" }] },
];

const jeddahNeighborhoods = [
  { nameEn: "Al Hamra", nameAr: "الحمراء", slug: "al-hamra", zone: "Central", lat: 21.5234, lng: 39.1678, avgAdrPeak: 1000, avgAdrHigh: 750, avgAdrLow: 500, avgNightlyRate: 700, walkTimeToLandmark: "10 min to Corniche", descriptionEn: "A prestigious residential district in central Jeddah, known for upscale living and proximity to the Corniche.", descriptionAr: "حي سكني مرموق في وسط جدة، يشتهر بالسكن الراقي والقرب من الكورنيش.", landmarks: [{ name: "Jeddah Corniche", nameAr: "كورنيش جدة" }] },
  { nameEn: "Al Rawdah", nameAr: "الروضة", slug: "al-rawdah-jeddah", zone: "Central", lat: 21.5123, lng: 39.1789, avgAdrPeak: 900, avgAdrHigh: 680, avgAdrLow: 450, avgNightlyRate: 630, walkTimeToLandmark: "5 min to Tahlia Street", descriptionEn: "A vibrant neighborhood centered around Tahlia Street, Jeddah's premier shopping and dining strip.", descriptionAr: "حي نابض بالحياة يتمركز حول شارع التحلية، وجهة التسوق والمطاعم الأولى في جدة.", landmarks: [{ name: "Tahlia Street", nameAr: "شارع التحلية" }] },
  { nameEn: "Al Zahra", nameAr: "الزهراء", slug: "al-zahra", zone: "Central", lat: 21.5345, lng: 39.1567, avgAdrPeak: 850, avgAdrHigh: 640, avgAdrLow: 420, avgNightlyRate: 600, walkTimeToLandmark: "8 min to Red Sea Mall", descriptionEn: "A well-established residential area with excellent amenities and shopping centers.", descriptionAr: "منطقة سكنية راسخة بمرافق ممتازة ومراكز تسوق.", landmarks: [{ name: "Red Sea Mall", nameAr: "ردسي مول" }] },
  { nameEn: "Obhur", nameAr: "أبحر", slug: "obhur", zone: "North", lat: 21.6234, lng: 39.1123, avgAdrPeak: 1200, avgAdrHigh: 900, avgAdrLow: 600, avgNightlyRate: 800, walkTimeToLandmark: "At the waterfront", descriptionEn: "A premium beachfront area in northern Jeddah, popular for luxury resorts and water activities.", descriptionAr: "منطقة شاطئية متميزة في شمال جدة، مشهورة بالمنتجعات الفاخرة والأنشطة المائية.", landmarks: [{ name: "Obhur Beach", nameAr: "شاطئ أبحر" }, { name: "Jeddah Yacht Club", nameAr: "نادي جدة لليخوت" }] },
  { nameEn: "Al Shati", nameAr: "الشاطئ", slug: "al-shati", zone: "West", lat: 21.5567, lng: 39.1234, avgAdrPeak: 1100, avgAdrHigh: 830, avgAdrLow: 550, avgNightlyRate: 750, walkTimeToLandmark: "On the Corniche", descriptionEn: "A waterfront neighborhood along the Jeddah Corniche, offering stunning Red Sea views.", descriptionAr: "حي على الواجهة البحرية على كورنيش جدة، يوفر إطلالات خلابة على البحر الأحمر.", landmarks: [{ name: "Jeddah Corniche", nameAr: "كورنيش جدة" }, { name: "King Fahd Fountain", nameAr: "نافورة الملك فهد" }] },
  { nameEn: "Al Andalus", nameAr: "الأندلس", slug: "al-andalus", zone: "Central", lat: 21.5012, lng: 39.1912, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 400, avgNightlyRate: 560, walkTimeToLandmark: "10 min to Mall of Arabia", descriptionEn: "A popular residential area with diverse housing options and commercial centers.", descriptionAr: "منطقة سكنية شعبية بخيارات سكنية متنوعة ومراكز تجارية.", landmarks: [{ name: "Mall of Arabia", nameAr: "مول العرب" }] },
  { nameEn: "Al Salamah", nameAr: "السلامة", slug: "al-salamah", zone: "Central", lat: 21.5189, lng: 39.1645, avgAdrPeak: 850, avgAdrHigh: 640, avgAdrLow: 420, avgNightlyRate: 600, walkTimeToLandmark: "7 min to Tahlia Street", descriptionEn: "A central neighborhood with a mix of residential and commercial properties.", descriptionAr: "حي مركزي يجمع بين العقارات السكنية والتجارية.", landmarks: [{ name: "Stars Avenue Mall", nameAr: "ستارز أفينيو مول" }] },
  { nameEn: "Al Balad", nameAr: "البلد", slug: "al-balad", zone: "Historic", lat: 21.4856, lng: 39.1867, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 350, avgNightlyRate: 480, walkTimeToLandmark: "In the historic district", descriptionEn: "Jeddah's historic district and UNESCO World Heritage site, featuring traditional Hejazi architecture.", descriptionAr: "الحي التاريخي في جدة وموقع تراث عالمي لليونسكو، يتميز بالعمارة الحجازية التقليدية.", landmarks: [{ name: "Al-Balad Historic District", nameAr: "حي البلد التاريخي" }, { name: "Nassif House", nameAr: "بيت نصيف" }] },
  { nameEn: "Al Muhammadiyah", nameAr: "المحمدية", slug: "al-muhammadiyah-jeddah", zone: "North", lat: 21.5789, lng: 39.1456, avgAdrPeak: 750, avgAdrHigh: 560, avgAdrLow: 380, avgNightlyRate: 520, walkTimeToLandmark: "Near Al Salam Mall", descriptionEn: "A growing residential area in northern Jeddah with modern developments.", descriptionAr: "منطقة سكنية متنامية في شمال جدة بتطويرات حديثة.", landmarks: [{ name: "Al Salam Mall", nameAr: "السلام مول" }] },
  { nameEn: "Al Marwah", nameAr: "المروة", slug: "al-marwah", zone: "Central", lat: 21.5067, lng: 39.1734, avgAdrPeak: 750, avgAdrHigh: 560, avgAdrLow: 380, avgNightlyRate: 520, walkTimeToLandmark: "5 min to Heraa Street", descriptionEn: "A central residential neighborhood with good access to major roads and shopping.", descriptionAr: "حي سكني مركزي بسهولة الوصول للطرق الرئيسية والتسوق.", landmarks: [{ name: "Heraa International Street", nameAr: "شارع حراء الدولي" }] },
  { nameEn: "Al Khalidiyah", nameAr: "الخالدية", slug: "al-khalidiyah", zone: "Central", lat: 21.5234, lng: 39.1567, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 400, avgNightlyRate: 560, walkTimeToLandmark: "Near Khalidiyah Mall", descriptionEn: "A well-known residential area with a mix of apartments and villas.", descriptionAr: "منطقة سكنية معروفة بمزيج من الشقق والفلل.", landmarks: [{ name: "Khalidiyah Mall", nameAr: "الخالدية مول" }] },
  { nameEn: "Al Faisaliyah", nameAr: "الفيصلية", slug: "al-faisaliyah-jeddah", zone: "Central", lat: 21.4978, lng: 39.1823, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 350, avgNightlyRate: 480, walkTimeToLandmark: "10 min to Al Balad", descriptionEn: "A traditional neighborhood near the historic center with authentic local character.", descriptionAr: "حي تقليدي قرب المركز التاريخي بطابع محلي أصيل.", landmarks: [{ name: "Bab Makkah", nameAr: "باب مكة" }] },
  { nameEn: "Briman", nameAr: "بريمان", slug: "briman", zone: "South", lat: 21.4567, lng: 39.2012, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 300, avgNightlyRate: 400, walkTimeToLandmark: "15 min to Airport", descriptionEn: "A southern Jeddah neighborhood with affordable options near the airport.", descriptionAr: "حي في جنوب جدة بخيارات بأسعار معقولة قرب المطار.", landmarks: [{ name: "King Abdulaziz Airport", nameAr: "مطار الملك عبدالعزيز" }] },
  { nameEn: "Al Naeem", nameAr: "النعيم", slug: "al-naeem-jeddah", zone: "North", lat: 21.5678, lng: 39.1345, avgAdrPeak: 750, avgAdrHigh: 560, avgAdrLow: 380, avgNightlyRate: 520, walkTimeToLandmark: "Near Jeddah Park", descriptionEn: "A residential area in northern Jeddah with parks and family amenities.", descriptionAr: "منطقة سكنية في شمال جدة بحدائق ومرافق عائلية.", landmarks: [{ name: "Jeddah Park", nameAr: "جدة بارك" }] },
  { nameEn: "Al Safa", nameAr: "الصفا", slug: "al-safa", zone: "Central", lat: 21.5145, lng: 39.1712, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 400, avgNightlyRate: 560, walkTimeToLandmark: "Near Safa Park", descriptionEn: "A central residential neighborhood with established infrastructure and green spaces.", descriptionAr: "حي سكني مركزي ببنية تحتية راسخة ومساحات خضراء.", landmarks: [{ name: "Safa Park", nameAr: "حديقة الصفا" }] },
  { nameEn: "Al Basateen", nameAr: "البساتين", slug: "al-basateen", zone: "East", lat: 21.4912, lng: 39.2123, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 300, avgNightlyRate: 400, walkTimeToLandmark: "Near Haramain Train Station", descriptionEn: "An eastern Jeddah neighborhood near the Haramain high-speed train station.", descriptionAr: "حي في شرق جدة قرب محطة قطار الحرمين السريع.", landmarks: [{ name: "Haramain Train Station", nameAr: "محطة قطار الحرمين" }] },
  { nameEn: "Al Rehab", nameAr: "الرحاب", slug: "al-rehab-jeddah", zone: "North", lat: 21.5912, lng: 39.1234, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 350, avgNightlyRate: 480, walkTimeToLandmark: "Near King Abdullah Sports City", descriptionEn: "A northern Jeddah neighborhood near major sports and entertainment venues.", descriptionAr: "حي في شمال جدة قرب المرافق الرياضية والترفيهية الرئيسية.", landmarks: [{ name: "King Abdullah Sports City", nameAr: "مدينة الملك عبدالله الرياضية" }] },
  { nameEn: "Al Aziziyah", nameAr: "العزيزية", slug: "al-aziziyah-jeddah", zone: "South", lat: 21.4678, lng: 39.2034, avgAdrPeak: 550, avgAdrHigh: 420, avgAdrLow: 280, avgNightlyRate: 370, walkTimeToLandmark: "Near Airport", descriptionEn: "A southern neighborhood with convenient airport access and affordable accommodations.", descriptionAr: "حي جنوبي بسهولة الوصول للمطار وإقامات بأسعار معقولة.", landmarks: [{ name: "King Abdulaziz Airport", nameAr: "مطار الملك عبدالعزيز" }] },
  { nameEn: "Al Bawadi", nameAr: "البوادي", slug: "al-bawadi", zone: "East", lat: 21.5034, lng: 39.2234, avgAdrPeak: 650, avgAdrHigh: 480, avgAdrLow: 320, avgNightlyRate: 430, walkTimeToLandmark: "Near Al Bawadi Mall", descriptionEn: "An eastern Jeddah neighborhood with modern shopping and residential developments.", descriptionAr: "حي في شرق جدة بتطويرات تسوق وسكنية حديثة.", landmarks: [{ name: "Al Bawadi Mall", nameAr: "البوادي مول" }] },
  { nameEn: "Al Nahdah", nameAr: "النهضة", slug: "al-nahdah-jeddah", zone: "East", lat: 21.5189, lng: 39.2145, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 300, avgNightlyRate: 400, walkTimeToLandmark: "Near Jeddah Mall", descriptionEn: "A developing eastern neighborhood with new residential and commercial projects.", descriptionAr: "حي شرقي متطور بمشاريع سكنية وتجارية جديدة.", landmarks: [{ name: "Jeddah Mall", nameAr: "جدة مول" }] },
  { nameEn: "Al Wahah", nameAr: "الواحة", slug: "al-wahah", zone: "North", lat: 21.5567, lng: 39.1567, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 350, avgNightlyRate: 480, walkTimeToLandmark: "Near Wahah Mall", descriptionEn: "A northern residential area with modern amenities and green spaces.", descriptionAr: "منطقة سكنية شمالية بمرافق حديثة ومساحات خضراء.", landmarks: [{ name: "Wahah Mall", nameAr: "الواحة مول" }] },
];

const madinahNeighborhoods = [
  { nameEn: "Al Haram District", nameAr: "حي الحرم", slug: "al-haram-district", zone: "Central", lat: 24.4672, lng: 39.6112, avgAdrPeak: 2000, avgAdrHigh: 1500, avgAdrLow: 800, avgNightlyRate: 1200, walkTimeToLandmark: "Walking distance to Al-Masjid an-Nabawi", descriptionEn: "The most prestigious area in Madinah, surrounding the Prophet's Mosque. Premium accommodations for pilgrims.", descriptionAr: "أرقى منطقة في المدينة المنورة، محيطة بالمسجد النبوي. إقامات متميزة للحجاج والزوار.", landmarks: [{ name: "Al-Masjid an-Nabawi", nameAr: "المسجد النبوي" }, { name: "Rawdah", nameAr: "الروضة الشريفة" }] },
  { nameEn: "Al Aziziyah", nameAr: "العزيزية", slug: "al-aziziyah-madinah", zone: "South", lat: 24.4512, lng: 39.6234, avgAdrPeak: 1200, avgAdrHigh: 900, avgAdrLow: 500, avgNightlyRate: 750, walkTimeToLandmark: "10 min to Al-Masjid an-Nabawi", descriptionEn: "A popular area for pilgrims, offering a range of accommodations near the Prophet's Mosque.", descriptionAr: "منطقة شعبية للحجاج، تقدم مجموعة من الإقامات قرب المسجد النبوي.", landmarks: [{ name: "Al-Masjid an-Nabawi", nameAr: "المسجد النبوي" }] },
  { nameEn: "Al Khalidiyah", nameAr: "الخالدية", slug: "al-khalidiyah-madinah", zone: "West", lat: 24.4734, lng: 39.5912, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 350, avgNightlyRate: 520, walkTimeToLandmark: "15 min to Al-Masjid an-Nabawi", descriptionEn: "A residential area west of the city center with good access to the Prophet's Mosque.", descriptionAr: "منطقة سكنية غرب وسط المدينة بسهولة الوصول للمسجد النبوي.", landmarks: [{ name: "Quba Mosque", nameAr: "مسجد قباء" }] },
  { nameEn: "Quba", nameAr: "قباء", slug: "quba", zone: "South-West", lat: 24.4389, lng: 39.6134, avgAdrPeak: 900, avgAdrHigh: 680, avgAdrLow: 400, avgNightlyRate: 580, walkTimeToLandmark: "At Quba Mosque", descriptionEn: "Home to the historic Quba Mosque, the first mosque built in Islam. A significant pilgrimage site.", descriptionAr: "موطن مسجد قباء التاريخي، أول مسجد بُني في الإسلام. موقع حج مهم.", landmarks: [{ name: "Quba Mosque", nameAr: "مسجد قباء" }, { name: "Quba Walk", nameAr: "ممشى قباء" }] },
  { nameEn: "Al Uyun", nameAr: "العيون", slug: "al-uyun", zone: "North", lat: 24.4912, lng: 39.5978, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 320, avgNightlyRate: 450, walkTimeToLandmark: "20 min to Al-Masjid an-Nabawi", descriptionEn: "A residential neighborhood in northern Madinah with modern housing developments.", descriptionAr: "حي سكني في شمال المدينة بتطويرات سكنية حديثة.", landmarks: [{ name: "Al Uyun Park", nameAr: "حديقة العيون" }] },
  { nameEn: "Uhud", nameAr: "أحد", slug: "uhud", zone: "North", lat: 24.5012, lng: 39.6123, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 280, avgNightlyRate: 380, walkTimeToLandmark: "At Mount Uhud", descriptionEn: "Located near the historic Mount Uhud, site of the famous Battle of Uhud.", descriptionAr: "يقع بالقرب من جبل أحد التاريخي، موقع معركة أحد الشهيرة.", landmarks: [{ name: "Mount Uhud", nameAr: "جبل أحد" }, { name: "Uhud Martyrs Cemetery", nameAr: "مقبرة شهداء أحد" }] },
  { nameEn: "Al Iskan", nameAr: "الإسكان", slug: "al-iskan", zone: "East", lat: 24.4567, lng: 39.6345, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 280, avgNightlyRate: 380, walkTimeToLandmark: "15 min to Al-Masjid an-Nabawi", descriptionEn: "A residential area in eastern Madinah with affordable housing options.", descriptionAr: "منطقة سكنية في شرق المدينة بخيارات سكنية بأسعار معقولة.", landmarks: [{ name: "Prince Mohammed bin Abdulaziz Hospital", nameAr: "مستشفى الأمير محمد بن عبدالعزيز" }] },
  { nameEn: "Al Ranuna", nameAr: "الرانوناء", slug: "al-ranuna", zone: "South", lat: 24.4345, lng: 39.6078, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 320, avgNightlyRate: 450, walkTimeToLandmark: "Near Quba Mosque", descriptionEn: "A quiet residential area near Quba Mosque with a traditional atmosphere.", descriptionAr: "منطقة سكنية هادئة قرب مسجد قباء بأجواء تقليدية.", landmarks: [{ name: "Quba Mosque", nameAr: "مسجد قباء" }] },
  { nameEn: "Al Arid", nameAr: "العارض", slug: "al-arid-madinah", zone: "North-West", lat: 24.4834, lng: 39.5823, avgAdrPeak: 550, avgAdrHigh: 420, avgAdrLow: 260, avgNightlyRate: 350, walkTimeToLandmark: "25 min to Al-Masjid an-Nabawi", descriptionEn: "A developing area in northwestern Madinah with new residential projects.", descriptionAr: "منطقة متطورة في شمال غرب المدينة بمشاريع سكنية جديدة.", landmarks: [{ name: "Al Arid Park", nameAr: "حديقة العارض" }] },
  { nameEn: "Al Salam", nameAr: "السلام", slug: "al-salam-madinah", zone: "West", lat: 24.4678, lng: 39.5789, avgAdrPeak: 650, avgAdrHigh: 480, avgAdrLow: 300, avgNightlyRate: 420, walkTimeToLandmark: "20 min to Al-Masjid an-Nabawi", descriptionEn: "A western residential neighborhood with modern amenities and good connectivity.", descriptionAr: "حي سكني غربي بمرافق حديثة وتوصيلات جيدة.", landmarks: [{ name: "Al Salam Park", nameAr: "حديقة السلام" }] },
  { nameEn: "Al Nakhil", nameAr: "النخيل", slug: "al-nakhil-madinah", zone: "North-East", lat: 24.4912, lng: 39.6234, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 280, avgNightlyRate: 380, walkTimeToLandmark: "18 min to Al-Masjid an-Nabawi", descriptionEn: "A northeastern residential area with palm-lined streets and family amenities.", descriptionAr: "منطقة سكنية شمالية شرقية بشوارع مظللة بالنخيل ومرافق عائلية.", landmarks: [{ name: "Al Nakhil Park", nameAr: "حديقة النخيل" }] },
  { nameEn: "Al Qiblatayn", nameAr: "القبلتين", slug: "al-qiblatayn", zone: "North-West", lat: 24.4789, lng: 39.5912, avgAdrPeak: 700, avgAdrHigh: 520, avgAdrLow: 320, avgNightlyRate: 450, walkTimeToLandmark: "At Qiblatayn Mosque", descriptionEn: "Named after the historic Qiblatayn Mosque, where the direction of prayer was changed.", descriptionAr: "سُمي نسبة لمسجد القبلتين التاريخي، حيث تم تحويل اتجاه القبلة.", landmarks: [{ name: "Qiblatayn Mosque", nameAr: "مسجد القبلتين" }] },
  { nameEn: "Bani Muawiyah", nameAr: "بني معاوية", slug: "bani-muawiyah", zone: "East", lat: 24.4623, lng: 39.6378, avgAdrPeak: 500, avgAdrHigh: 380, avgAdrLow: 240, avgNightlyRate: 320, walkTimeToLandmark: "20 min to Al-Masjid an-Nabawi", descriptionEn: "An eastern Madinah neighborhood with affordable accommodation options.", descriptionAr: "حي في شرق المدينة بخيارات إقامة بأسعار معقولة.", landmarks: [{ name: "Eastern Ring Road", nameAr: "الطريق الدائري الشرقي" }] },
  { nameEn: "Al Duwaimah", nameAr: "الدويمة", slug: "al-duwaimah", zone: "South-East", lat: 24.4423, lng: 39.6289, avgAdrPeak: 550, avgAdrHigh: 420, avgAdrLow: 260, avgNightlyRate: 350, walkTimeToLandmark: "12 min to Al-Masjid an-Nabawi", descriptionEn: "A southeastern neighborhood with traditional character and proximity to the city center.", descriptionAr: "حي جنوبي شرقي بطابع تقليدي وقرب من وسط المدينة.", landmarks: [{ name: "Al Duwaimah Market", nameAr: "سوق الدويمة" }] },
  { nameEn: "Al Mughaisilah", nameAr: "المغيسلة", slug: "al-mughaisilah", zone: "South", lat: 24.4289, lng: 39.6167, avgAdrPeak: 500, avgAdrHigh: 380, avgAdrLow: 240, avgNightlyRate: 320, walkTimeToLandmark: "Near Quba area", descriptionEn: "A southern Madinah neighborhood near the Quba area with affordable options.", descriptionAr: "حي في جنوب المدينة قرب منطقة قباء بخيارات بأسعار معقولة.", landmarks: [{ name: "Quba Walk", nameAr: "ممشى قباء" }] },
  { nameEn: "Sayed Al Shuhada", nameAr: "سيد الشهداء", slug: "sayed-al-shuhada", zone: "North", lat: 24.4956, lng: 39.6089, avgAdrPeak: 650, avgAdrHigh: 480, avgAdrLow: 300, avgNightlyRate: 420, walkTimeToLandmark: "Near Mount Uhud", descriptionEn: "Located near the Uhud battlefield, a historically significant area for Islamic heritage.", descriptionAr: "يقع بالقرب من ساحة معركة أحد، منطقة ذات أهمية تاريخية للتراث الإسلامي.", landmarks: [{ name: "Uhud Battlefield", nameAr: "ساحة معركة أحد" }] },
  { nameEn: "Al Jumu'ah", nameAr: "الجمعة", slug: "al-jumuah", zone: "South-West", lat: 24.4412, lng: 39.5934, avgAdrPeak: 600, avgAdrHigh: 450, avgAdrLow: 280, avgNightlyRate: 380, walkTimeToLandmark: "Near Al Jumu'ah Mosque", descriptionEn: "A southwestern neighborhood named after the historic Friday Mosque.", descriptionAr: "حي جنوبي غربي سُمي نسبة لمسجد الجمعة التاريخي.", landmarks: [{ name: "Al Jumu'ah Mosque", nameAr: "مسجد الجمعة" }] },
  { nameEn: "Al Awali", nameAr: "العوالي", slug: "al-awali", zone: "South-East", lat: 24.4345, lng: 39.6345, avgAdrPeak: 550, avgAdrHigh: 420, avgAdrLow: 260, avgNightlyRate: 350, walkTimeToLandmark: "Near Al Awali Park", descriptionEn: "A southeastern residential area with a mix of traditional and modern housing.", descriptionAr: "منطقة سكنية جنوبية شرقية بمزيج من السكن التقليدي والحديث.", landmarks: [{ name: "Al Awali Park", nameAr: "حديقة العوالي" }] },
  { nameEn: "Al Barakah", nameAr: "البركة", slug: "al-barakah", zone: "Central", lat: 24.4589, lng: 39.6067, avgAdrPeak: 800, avgAdrHigh: 600, avgAdrLow: 380, avgNightlyRate: 520, walkTimeToLandmark: "10 min to Al-Masjid an-Nabawi", descriptionEn: "A central neighborhood with good access to the Prophet's Mosque and city amenities.", descriptionAr: "حي مركزي بسهولة الوصول للمسجد النبوي ومرافق المدينة.", landmarks: [{ name: "Al-Masjid an-Nabawi", nameAr: "المسجد النبوي" }] },
  { nameEn: "Yanbu Al Nakhl", nameAr: "ينبع النخل", slug: "yanbu-al-nakhl", zone: "West", lat: 24.4534, lng: 39.5734, avgAdrPeak: 500, avgAdrHigh: 380, avgAdrLow: 240, avgNightlyRate: 320, walkTimeToLandmark: "30 min to Al-Masjid an-Nabawi", descriptionEn: "A western area known for its date palm gardens and traditional atmosphere.", descriptionAr: "منطقة غربية تشتهر ببساتين النخيل وأجوائها التقليدية.", landmarks: [{ name: "Date Palm Gardens", nameAr: "بساتين النخيل" }] },
];

const allNeighborhoods = [
  ...riyadhNeighborhoods.map(n => ({ ...n, citySlug: "riyadh" })),
  ...jeddahNeighborhoods.map(n => ({ ...n, citySlug: "jeddah" })),
  ...madinahNeighborhoods.map(n => ({ ...n, citySlug: "madinah" })),
];

console.log(`Total neighborhoods: ${allNeighborhoods.length}`);

for (const nh of allNeighborhoods) {
  const cityId = cityMap[nh.citySlug];
  await conn.execute(
    `INSERT INTO neighborhoods (cityId, nameEn, nameAr, slug, zone, descriptionEn, descriptionAr, landmarks, avgAdrPeak, avgAdrHigh, avgAdrLow, latitude, longitude, avgNightlyRate, walkTimeToLandmark, isActive) 
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 1) 
     ON DUPLICATE KEY UPDATE nameAr=VALUES(nameAr), zone=VALUES(zone), descriptionEn=VALUES(descriptionEn), descriptionAr=VALUES(descriptionAr), landmarks=VALUES(landmarks), avgAdrPeak=VALUES(avgAdrPeak), avgAdrHigh=VALUES(avgAdrHigh), avgAdrLow=VALUES(avgAdrLow), latitude=VALUES(latitude), longitude=VALUES(longitude), avgNightlyRate=VALUES(avgNightlyRate), walkTimeToLandmark=VALUES(walkTimeToLandmark)`,
    [cityId, nh.nameEn, nh.nameAr, nh.slug, nh.zone, nh.descriptionEn, nh.descriptionAr, JSON.stringify(nh.landmarks), nh.avgAdrPeak, nh.avgAdrHigh, nh.avgAdrLow, nh.lat, nh.lng, nh.avgNightlyRate, nh.walkTimeToLandmark]
  );
}
console.log("✅ Neighborhoods seeded");

// ─── Demo Properties ─────────────────────────────────────────────────
const [nhRows] = await conn.execute("SELECT id, cityId, nameEn, slug FROM neighborhoods LIMIT 20");
const demoProperties = [
  { titleEn: "Luxury Studio in Al Olaya", titleAr: "استوديو فاخر في العليا", type: "studio", bedrooms: 0, bathrooms: 1, maxGuests: 2, sizeSqm: 45, pricePeak: 800, priceHigh: 600, priceLow: 400 },
  { titleEn: "Modern 1BR Apartment - Kingdom Tower View", titleAr: "شقة غرفة واحدة حديثة - إطلالة برج المملكة", type: "1br", bedrooms: 1, bathrooms: 1, maxGuests: 3, sizeSqm: 65, pricePeak: 1200, priceHigh: 900, priceLow: 600 },
  { titleEn: "Spacious 2BR Family Apartment", titleAr: "شقة عائلية واسعة غرفتين", type: "2br", bedrooms: 2, bathrooms: 2, maxGuests: 5, sizeSqm: 110, pricePeak: 1500, priceHigh: 1100, priceLow: 750 },
  { titleEn: "Premium 3BR Villa with Pool", titleAr: "فيلا 3 غرف متميزة مع مسبح", type: "villa", bedrooms: 3, bathrooms: 3, maxGuests: 8, sizeSqm: 250, pricePeak: 2500, priceHigh: 1800, priceLow: 1200 },
  { titleEn: "Executive Suite - Business District", titleAr: "جناح تنفيذي - الحي المالي", type: "1br", bedrooms: 1, bathrooms: 1, maxGuests: 2, sizeSqm: 55, pricePeak: 1000, priceHigh: 750, priceLow: 500 },
  { titleEn: "Cozy 1BR near Corniche", titleAr: "شقة مريحة غرفة واحدة قرب الكورنيش", type: "1br", bedrooms: 1, bathrooms: 1, maxGuests: 3, sizeSqm: 60, pricePeak: 900, priceHigh: 680, priceLow: 450 },
  { titleEn: "Beachfront 2BR Apartment", titleAr: "شقة غرفتين على الشاطئ", type: "2br", bedrooms: 2, bathrooms: 2, maxGuests: 5, sizeSqm: 100, pricePeak: 1800, priceHigh: 1300, priceLow: 850 },
  { titleEn: "Historic Al Balad Loft", titleAr: "لوفت تاريخي في البلد", type: "1br", bedrooms: 1, bathrooms: 1, maxGuests: 2, sizeSqm: 50, pricePeak: 700, priceHigh: 520, priceLow: 350 },
  { titleEn: "Pilgrim Suite near Prophet's Mosque", titleAr: "جناح الحاج قرب المسجد النبوي", type: "2br", bedrooms: 2, bathrooms: 2, maxGuests: 6, sizeSqm: 90, pricePeak: 2000, priceHigh: 1500, priceLow: 800 },
  { titleEn: "Family Villa in Quba", titleAr: "فيلا عائلية في قباء", type: "villa", bedrooms: 4, bathrooms: 3, maxGuests: 10, sizeSqm: 300, pricePeak: 2500, priceHigh: 1800, priceLow: 1000 },
  { titleEn: "Deluxe 2BR near KAFD", titleAr: "شقة فاخرة غرفتين قرب كافد", type: "2br", bedrooms: 2, bathrooms: 2, maxGuests: 4, sizeSqm: 95, pricePeak: 1600, priceHigh: 1200, priceLow: 800 },
  { titleEn: "Charming Studio in Al Nakheel", titleAr: "استوديو ساحر في النخيل", type: "studio", bedrooms: 0, bathrooms: 1, maxGuests: 2, sizeSqm: 40, pricePeak: 700, priceHigh: 520, priceLow: 350 },
];

for (let i = 0; i < demoProperties.length && i < nhRows.length; i++) {
  const p = demoProperties[i];
  const nh = nhRows[i];
  const amenities = ["WiFi", "AC", "Kitchen", "Washer", "TV", "Parking"];
  await conn.execute(
    `INSERT INTO properties (titleEn, titleAr, descriptionEn, descriptionAr, propertyType, cityId, neighborhoodId, bedrooms, bathrooms, maxGuests, sizeSqm, pricePeak, priceHigh, priceLow, amenities, images, isFeatured, propertyStatus) 
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, '[]', ?, 'active')`,
    [p.titleEn, p.titleAr, `A beautiful ${p.type} in ${nh.nameEn}. Fully furnished with modern amenities.`, `${p.titleAr} - مفروشة بالكامل بمرافق حديثة.`, p.type, nh.cityId, nh.id, p.bedrooms, p.bathrooms, p.maxGuests, p.sizeSqm, p.pricePeak, p.priceHigh, p.priceLow, JSON.stringify(amenities), i < 6]
  );
}
console.log("✅ Properties seeded");

// ─── Blog Posts ──────────────────────────────────────────────────────
const blogPosts = [
  { titleEn: "Saudi Vision 2030: Transforming the Tourism Landscape", titleAr: "رؤية السعودية 2030: تحويل المشهد السياحي", slug: "vision-2030-tourism", category: "saudi_tourism", excerptEn: "How Vision 2030 is reshaping Saudi Arabia's tourism sector and creating unprecedented opportunities.", excerptAr: "كيف تعيد رؤية 2030 تشكيل قطاع السياحة في المملكة العربية السعودية وتخلق فرصاً غير مسبوقة.", contentEn: "Saudi Arabia's Vision 2030 has set ambitious targets for the tourism sector, aiming to welcome 150 million visitors annually by 2030. This transformation is creating massive opportunities in the short-term rental market...", contentAr: "وضعت رؤية المملكة العربية السعودية 2030 أهدافاً طموحة لقطاع السياحة، تهدف لاستقبال 150 مليون زائر سنوياً بحلول 2030. هذا التحول يخلق فرصاً هائلة في سوق الإيجار القصير..." },
  { titleEn: "Top 10 Neighborhoods for Short-Term Rentals in Riyadh", titleAr: "أفضل 10 أحياء للإيجار القصير في الرياض", slug: "top-neighborhoods-riyadh", category: "property_investment", excerptEn: "Discover the most profitable neighborhoods for short-term rental investments in Saudi Arabia's capital.", excerptAr: "اكتشف الأحياء الأكثر ربحية للاستثمار في الإيجار القصير في عاصمة المملكة.", contentEn: "Riyadh's short-term rental market is booming, driven by business travel, entertainment events, and growing tourism...", contentAr: "سوق الإيجار القصير في الرياض يشهد ازدهاراً كبيراً، مدفوعاً بسفر الأعمال والفعاليات الترفيهية والسياحة المتنامية..." },
  { titleEn: "A Complete Guide to Jeddah: Where History Meets the Sea", titleAr: "دليل شامل لجدة: حيث يلتقي التاريخ بالبحر", slug: "jeddah-travel-guide", category: "travel_guides", excerptEn: "Everything you need to know about visiting Jeddah, from historic Al-Balad to the stunning Red Sea coast.", excerptAr: "كل ما تحتاج معرفته عن زيارة جدة، من حي البلد التاريخي إلى ساحل البحر الأحمر الخلاب.", contentEn: "Jeddah, the commercial capital of Saudi Arabia, offers a unique blend of history, culture, and modern entertainment...", contentAr: "جدة، العاصمة التجارية للمملكة العربية السعودية، تقدم مزيجاً فريداً من التاريخ والثقافة والترفيه الحديث..." },
  { titleEn: "The Rise of Short-Term Rentals in Saudi Arabia", titleAr: "صعود الإيجارات القصيرة في المملكة العربية السعودية", slug: "rise-short-term-rentals", category: "industry_news", excerptEn: "Saudi Arabia's short-term rental market is experiencing explosive growth. Here's what's driving it.", excerptAr: "سوق الإيجار القصير في المملكة يشهد نمواً هائلاً. إليك ما يدفع هذا النمو.", contentEn: "The short-term rental industry in Saudi Arabia has grown by over 200% in the past three years...", contentAr: "نما قطاع الإيجار القصير في المملكة العربية السعودية بأكثر من 200% في السنوات الثلاث الماضية..." },
  { titleEn: "Madinah: A Spiritual Journey and Modern Hospitality", titleAr: "المدينة المنورة: رحلة روحانية وضيافة حديثة", slug: "madinah-spiritual-guide", category: "travel_guides", excerptEn: "Discover the spiritual significance and modern hospitality offerings of the Prophet's city.", excerptAr: "اكتشف الأهمية الروحية وعروض الضيافة الحديثة في مدينة الرسول.", contentEn: "Madinah, the radiant city, welcomes millions of visitors each year seeking spiritual fulfillment...", contentAr: "المدينة المنورة تستقبل ملايين الزوار سنوياً الباحثين عن الراحة الروحية..." },
  { titleEn: "How to Maximize Your Property's Revenue with CoBnB", titleAr: "كيف تحقق أقصى عائد من عقارك مع CoBnB", slug: "maximize-revenue-cobnb", category: "property_investment", excerptEn: "Learn how our 70/30 profit-sharing model and dynamic pricing can boost your rental income.", excerptAr: "تعرف على كيفية زيادة دخلك من الإيجار من خلال نموذج تقاسم الأرباح 70/30 والتسعير الديناميكي.", contentEn: "At CoBnB, we believe property owners deserve the lion's share of their rental income...", contentAr: "في CoBnB، نؤمن بأن ملاك العقارات يستحقون الحصة الأكبر من دخل الإيجار..." },
];

for (const post of blogPosts) {
  await conn.execute(
    `INSERT INTO blog_posts (titleEn, titleAr, slug, blogCategory, excerptEn, excerptAr, contentEn, contentAr, blogStatus, publishedAt) 
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'published', NOW()) 
     ON DUPLICATE KEY UPDATE titleAr=VALUES(titleAr)`,
    [post.titleEn, post.titleAr, post.slug, post.category, post.excerptEn, post.excerptAr, post.contentEn, post.contentAr]
  );
}
console.log("✅ Blog posts seeded");

await conn.end();
console.log("✅ Database seeding complete!");
console.log(`Cities: ${cities.length}, Neighborhoods: ${allNeighborhoods.length}, Properties: ${demoProperties.length}, Blog posts: ${blogPosts.length}`);
